// Generated by gencpp from file lab2_communication/robot_id.msg
// DO NOT EDIT!


#ifndef LAB2_COMMUNICATION_MESSAGE_ROBOT_ID_H
#define LAB2_COMMUNICATION_MESSAGE_ROBOT_ID_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace lab2_communication
{
template <class ContainerAllocator>
struct robot_id_
{
  typedef robot_id_<ContainerAllocator> Type;

  robot_id_()
    : header()
    , id(0)
    , model()  {
    }
  robot_id_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , model(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _model_type;
  _model_type model;





  typedef boost::shared_ptr< ::lab2_communication::robot_id_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab2_communication::robot_id_<ContainerAllocator> const> ConstPtr;

}; // struct robot_id_

typedef ::lab2_communication::robot_id_<std::allocator<void> > robot_id;

typedef boost::shared_ptr< ::lab2_communication::robot_id > robot_idPtr;
typedef boost::shared_ptr< ::lab2_communication::robot_id const> robot_idConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab2_communication::robot_id_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab2_communication::robot_id_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lab2_communication::robot_id_<ContainerAllocator1> & lhs, const ::lab2_communication::robot_id_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.id == rhs.id &&
    lhs.model == rhs.model;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lab2_communication::robot_id_<ContainerAllocator1> & lhs, const ::lab2_communication::robot_id_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lab2_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lab2_communication::robot_id_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab2_communication::robot_id_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab2_communication::robot_id_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab2_communication::robot_id_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab2_communication::robot_id_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab2_communication::robot_id_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab2_communication::robot_id_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c2f9e6ea3b185d6a5046a4e13f05579";
  }

  static const char* value(const ::lab2_communication::robot_id_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c2f9e6ea3b185d6ULL;
  static const uint64_t static_value2 = 0xa5046a4e13f05579ULL;
};

template<class ContainerAllocator>
struct DataType< ::lab2_communication::robot_id_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab2_communication/robot_id";
  }

  static const char* value(const ::lab2_communication::robot_id_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab2_communication::robot_id_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int8 id\n"
"string model\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::lab2_communication::robot_id_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab2_communication::robot_id_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.model);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_id_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab2_communication::robot_id_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab2_communication::robot_id_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.id);
    s << indent << "model: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.model);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB2_COMMUNICATION_MESSAGE_ROBOT_ID_H
