// Generated by gencpp from file lab2_communication/Set_Robot_Model.msg
// DO NOT EDIT!


#ifndef LAB2_COMMUNICATION_MESSAGE_SET_ROBOT_MODEL_H
#define LAB2_COMMUNICATION_MESSAGE_SET_ROBOT_MODEL_H

#include <ros/service_traits.h>


#include <lab2_communication/Set_Robot_ModelRequest.h>
#include <lab2_communication/Set_Robot_ModelResponse.h>


namespace lab2_communication
{

struct Set_Robot_Model
{

typedef Set_Robot_ModelRequest Request;
typedef Set_Robot_ModelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Set_Robot_Model
} // namespace lab2_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lab2_communication::Set_Robot_Model > {
  static const char* value()
  {
    return "51cc362f6d06def3fd71b2dbe3614cc8";
  }

  static const char* value(const ::lab2_communication::Set_Robot_Model&) { return value(); }
};

template<>
struct DataType< ::lab2_communication::Set_Robot_Model > {
  static const char* value()
  {
    return "lab2_communication/Set_Robot_Model";
  }

  static const char* value(const ::lab2_communication::Set_Robot_Model&) { return value(); }
};


// service_traits::MD5Sum< ::lab2_communication::Set_Robot_ModelRequest> should match
// service_traits::MD5Sum< ::lab2_communication::Set_Robot_Model >
template<>
struct MD5Sum< ::lab2_communication::Set_Robot_ModelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lab2_communication::Set_Robot_Model >::value();
  }
  static const char* value(const ::lab2_communication::Set_Robot_ModelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab2_communication::Set_Robot_ModelRequest> should match
// service_traits::DataType< ::lab2_communication::Set_Robot_Model >
template<>
struct DataType< ::lab2_communication::Set_Robot_ModelRequest>
{
  static const char* value()
  {
    return DataType< ::lab2_communication::Set_Robot_Model >::value();
  }
  static const char* value(const ::lab2_communication::Set_Robot_ModelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lab2_communication::Set_Robot_ModelResponse> should match
// service_traits::MD5Sum< ::lab2_communication::Set_Robot_Model >
template<>
struct MD5Sum< ::lab2_communication::Set_Robot_ModelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lab2_communication::Set_Robot_Model >::value();
  }
  static const char* value(const ::lab2_communication::Set_Robot_ModelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab2_communication::Set_Robot_ModelResponse> should match
// service_traits::DataType< ::lab2_communication::Set_Robot_Model >
template<>
struct DataType< ::lab2_communication::Set_Robot_ModelResponse>
{
  static const char* value()
  {
    return DataType< ::lab2_communication::Set_Robot_Model >::value();
  }
  static const char* value(const ::lab2_communication::Set_Robot_ModelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LAB2_COMMUNICATION_MESSAGE_SET_ROBOT_MODEL_H
