// Generated by gencpp from file lab2_communication/Set_Robot_ModelRequest.msg
// DO NOT EDIT!


#ifndef LAB2_COMMUNICATION_MESSAGE_SET_ROBOT_MODELREQUEST_H
#define LAB2_COMMUNICATION_MESSAGE_SET_ROBOT_MODELREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lab2_communication
{
template <class ContainerAllocator>
struct Set_Robot_ModelRequest_
{
  typedef Set_Robot_ModelRequest_<ContainerAllocator> Type;

  Set_Robot_ModelRequest_()
    : model()  {
    }
  Set_Robot_ModelRequest_(const ContainerAllocator& _alloc)
    : model(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _model_type;
  _model_type model;





  typedef boost::shared_ptr< ::lab2_communication::Set_Robot_ModelRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab2_communication::Set_Robot_ModelRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Set_Robot_ModelRequest_

typedef ::lab2_communication::Set_Robot_ModelRequest_<std::allocator<void> > Set_Robot_ModelRequest;

typedef boost::shared_ptr< ::lab2_communication::Set_Robot_ModelRequest > Set_Robot_ModelRequestPtr;
typedef boost::shared_ptr< ::lab2_communication::Set_Robot_ModelRequest const> Set_Robot_ModelRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab2_communication::Set_Robot_ModelRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab2_communication::Set_Robot_ModelRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lab2_communication::Set_Robot_ModelRequest_<ContainerAllocator1> & lhs, const ::lab2_communication::Set_Robot_ModelRequest_<ContainerAllocator2> & rhs)
{
  return lhs.model == rhs.model;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lab2_communication::Set_Robot_ModelRequest_<ContainerAllocator1> & lhs, const ::lab2_communication::Set_Robot_ModelRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lab2_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lab2_communication::Set_Robot_ModelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab2_communication::Set_Robot_ModelRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab2_communication::Set_Robot_ModelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab2_communication::Set_Robot_ModelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab2_communication::Set_Robot_ModelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab2_communication::Set_Robot_ModelRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab2_communication::Set_Robot_ModelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0147e4f36cba5cda7fa39c089e493413";
  }

  static const char* value(const ::lab2_communication::Set_Robot_ModelRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0147e4f36cba5cdaULL;
  static const uint64_t static_value2 = 0x7fa39c089e493413ULL;
};

template<class ContainerAllocator>
struct DataType< ::lab2_communication::Set_Robot_ModelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab2_communication/Set_Robot_ModelRequest";
  }

  static const char* value(const ::lab2_communication::Set_Robot_ModelRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab2_communication::Set_Robot_ModelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string model\n"
;
  }

  static const char* value(const ::lab2_communication::Set_Robot_ModelRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab2_communication::Set_Robot_ModelRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.model);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Set_Robot_ModelRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab2_communication::Set_Robot_ModelRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab2_communication::Set_Robot_ModelRequest_<ContainerAllocator>& v)
  {
    s << indent << "model: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.model);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB2_COMMUNICATION_MESSAGE_SET_ROBOT_MODELREQUEST_H
