(cl:defpackage tr5_kinematics-srv
  (:use )
  (:export
   "DOFORWARDKINEMATICS"
   "<DOFORWARDKINEMATICS-REQUEST>"
   "DOFORWARDKINEMATICS-REQUEST"
   "<DOFORWARDKINEMATICS-RESPONSE>"
   "DOFORWARDKINEMATICS-RESPONSE"
   "DOINVERSEKINEMATICS"
   "<DOINVERSEKINEMATICS-REQUEST>"
   "DOINVERSEKINEMATICS-REQUEST"
   "<DOINVERSEKINEMATICS-RESPONSE>"
   "DOINVERSEKINEMATICS-RESPONSE"
  ))

