// Generated by gencpp from file tr5_robot_controller/KinematicModeRequest.msg
// DO NOT EDIT!


#ifndef TR5_ROBOT_CONTROLLER_MESSAGE_KINEMATICMODEREQUEST_H
#define TR5_ROBOT_CONTROLLER_MESSAGE_KINEMATICMODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tr5_robot_controller
{
template <class ContainerAllocator>
struct KinematicModeRequest_
{
  typedef KinematicModeRequest_<ContainerAllocator> Type;

  KinematicModeRequest_()
    : mode_value(0)  {
    }
  KinematicModeRequest_(const ContainerAllocator& _alloc)
    : mode_value(0)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_value_type;
  _mode_value_type mode_value;





  typedef boost::shared_ptr< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct KinematicModeRequest_

typedef ::tr5_robot_controller::KinematicModeRequest_<std::allocator<void> > KinematicModeRequest;

typedef boost::shared_ptr< ::tr5_robot_controller::KinematicModeRequest > KinematicModeRequestPtr;
typedef boost::shared_ptr< ::tr5_robot_controller::KinematicModeRequest const> KinematicModeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator1> & lhs, const ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode_value == rhs.mode_value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator1> & lhs, const ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tr5_robot_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd104cf2962786ef45793330ebf60a0d";
  }

  static const char* value(const ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd104cf2962786efULL;
  static const uint64_t static_value2 = 0x45793330ebf60a0dULL;
};

template<class ContainerAllocator>
struct DataType< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tr5_robot_controller/KinematicModeRequest";
  }

  static const char* value(const ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 mode_value\n"
;
  }

  static const char* value(const ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KinematicModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode_value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode_value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TR5_ROBOT_CONTROLLER_MESSAGE_KINEMATICMODEREQUEST_H
