// Generated by gencpp from file tr5_robot_controller/KinematicModeResponse.msg
// DO NOT EDIT!


#ifndef TR5_ROBOT_CONTROLLER_MESSAGE_KINEMATICMODERESPONSE_H
#define TR5_ROBOT_CONTROLLER_MESSAGE_KINEMATICMODERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tr5_robot_controller
{
template <class ContainerAllocator>
struct KinematicModeResponse_
{
  typedef KinematicModeResponse_<ContainerAllocator> Type;

  KinematicModeResponse_()
    : mode(false)  {
    }
  KinematicModeResponse_(const ContainerAllocator& _alloc)
    : mode(false)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::tr5_robot_controller::KinematicModeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tr5_robot_controller::KinematicModeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct KinematicModeResponse_

typedef ::tr5_robot_controller::KinematicModeResponse_<std::allocator<void> > KinematicModeResponse;

typedef boost::shared_ptr< ::tr5_robot_controller::KinematicModeResponse > KinematicModeResponsePtr;
typedef boost::shared_ptr< ::tr5_robot_controller::KinematicModeResponse const> KinematicModeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tr5_robot_controller::KinematicModeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tr5_robot_controller::KinematicModeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tr5_robot_controller::KinematicModeResponse_<ContainerAllocator1> & lhs, const ::tr5_robot_controller::KinematicModeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tr5_robot_controller::KinematicModeResponse_<ContainerAllocator1> & lhs, const ::tr5_robot_controller::KinematicModeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tr5_robot_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tr5_robot_controller::KinematicModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tr5_robot_controller::KinematicModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tr5_robot_controller::KinematicModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tr5_robot_controller::KinematicModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tr5_robot_controller::KinematicModeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tr5_robot_controller::KinematicModeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tr5_robot_controller::KinematicModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3124ebba8ebedcd8ba82847d482ceb7";
  }

  static const char* value(const ::tr5_robot_controller::KinematicModeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3124ebba8ebedcdULL;
  static const uint64_t static_value2 = 0x8ba82847d482ceb7ULL;
};

template<class ContainerAllocator>
struct DataType< ::tr5_robot_controller::KinematicModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tr5_robot_controller/KinematicModeResponse";
  }

  static const char* value(const ::tr5_robot_controller::KinematicModeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tr5_robot_controller::KinematicModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool mode\n"
;
  }

  static const char* value(const ::tr5_robot_controller::KinematicModeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tr5_robot_controller::KinematicModeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KinematicModeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tr5_robot_controller::KinematicModeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tr5_robot_controller::KinematicModeResponse_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TR5_ROBOT_CONTROLLER_MESSAGE_KINEMATICMODERESPONSE_H
